backend:
  name: git-gateway
  branch: main

# publish_mode: editorial_workflow
media_folder: "images/posts" # Media files will be stored in the repo under src/assets/images/posts
public_folder: "/images/posts" # The src attribute for uploaded media will begin with assets/images/posts

collections:
  - name: "categorias" # Used in routes, e.g., /admin/collections/blog
    label: "Categorías" # Used in the UI
    folder: "src/categorias" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false # Disable the editor preview and use instead 'preview links'
    fields: # The fields for each document, usually in front matter
      - { name: "title", label: "Nombre de Categoría" }
      - { name: "descripcion", label: "Descripción" }
  - name: "autores" # Used in routes, e.g., /admin/collections/blog
    label: "Autores" # Used in the UI
    folder: "src/autores" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false # Disable the editor preview and use instead 'preview links'
    fields: # The fields for each document, usually in front matter
      - { name: "title", label: "Nombre" }
      - { name: "correo", label: "Correo" }
      - { name: "imagen", label: "Imagen de autor", widget: "image" }
  - name: "ediciones" # Used in routes, e.g., /admin/collections/blog
    label: "Ediciones de Revista" # Used in the UI
    folder: "src/ediciones" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false # Disable the editor preview and use instead 'preview links'
    fields: # The fields for each document, usually in front matter
      - { name: "title", label: "Título de Edición" }
      - { name: "descripcion", label: "Descripción de Edición" }
      - { name: "fecha", label: "Mes y Año de Edición", widget: "date" }
      - { name: "imagen", label: "Imagen de Edición", widget: "image" }
      - { name: "enlace", label: "Enlace de Edición" }
  - name: "articulos" # Used in routes, e.g., /admin/collections/blog
    label: "Artículos" # Used in the UI
    folder: "src/articulos" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false # Disable the editor preview and use instead 'preview links'
    fields: # The fields for each document, usually in front matter
      - { name: "title", label: "Título" }
      - { name: "imagen", label: "Imagen del Artículo", widget: "image" }
      - { name: "descripcion", label: "Descripción" }
      - {
          label: "Autor",
          name: "autor",
          widget: "relation",
          collection: "autores",
          options_length: 50,
          search_fields: ["title"],
          value_field: "title",
          multiple: false,
        }
      - {
          label: "Correo del Autor",
          name: "correoautor",
          widget: "relation",
          collection: "autores",
          options_length: 50,
          search_fields: ["title"],
          value_field: "correo",
          multiple: false,
        }
      - { name: "fecha", label: "Fecha", widget: "date" }
      - {
          name: "categorias",
          label: "Categorías",
          widget: "list",
          field:
            {
              label: "Categoría",
              name: "categoria",
              widget: "relation",
              collection: "categorias",
              options_length: 50,
              search_fields: ["title"],
              value_field: "title",
              multiple: false,
            },
        }
      - {
          label: "Ediciones de Revista",
          name: "ediciones",
          widget: "relation",
          collection: "ediciones",
          options_length: 50,
          search_fields: ["title"],
          value_field: "title",
          multiple: false,
        }
      - { name: "body", label: "Contenido", widget: "markdown" }
      - {
          name: "highlight",
          label: "Highlight",
          widget: "boolean",
          default: false,
          hint: "Display posts in home's highlights",
        }
  - name: "publicidad" # Used in routes, e.g., /admin/collections/blog
    label: "Publicidad" # Used in the UI
    folder: "src/publicidad" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false # Disable the editor preview and use instead 'preview links'
    fields: # The fields for each document, usually in front matter
      - { name: "title", label: "Nombre de la Publciidad" }
      - { name: "adhorizontal", label: "Ad Horizontal", required: false }
      - {
          name: "enlaceadhorizontal",
          label: "Enlace de Redirección de Ad Horizontal",
          required: false,
        }
      - { name: "advertical", label: "Ad Vertical", required: false }
      - {
          name: "enlaceadvertical",
          label: "Enlace de Redirección de Ad Vertical",
          required: false,
        }
      - {
          name: "highlight",
          label: "Highlight",
          widget: "boolean",
          default: false,
          hint: "Display posts in home's highlights",
        }
